import type { PortfolioData } from "./types";

export const data: PortfolioData = {
  name: "Muhammet Sefa Kapısız",
  title: "Backend Engineer",
  email: "m.sefa06@hotmail.com",
  phone: "+90 555 881 1783",
  location: "Istanbul, Turkey",
  github: "https://github.com/sefakpsz",
  linkedin: "https://linkedin.com/in/sefakpsz",
  medium: "https://medium.com/@sefakpsz",
  profile:
    "Results-driven Backend Engineer with 4+ years of professional experience designing and delivering scalable, cloud-native systems in fintech and SaaS environments. Proven expertise in C#, .NET, and Node.js, with hands-on production experience across PostgreSQL, MongoDB, Redis, and RabbitMQ. Passionate about clean architecture, system performance, and delivering reliable software at scale.",
  skills: [
    {
      category: "Programming Languages",
      items: ["C#", "TypeScript", "JavaScript"],
    },
    {
      category: "Frameworks & Libraries",
      items: [
        ".NET",
        "Entity Framework",
        "Autofac",
        "XUnit",
        "Ocelot",
        "MediatR",
        "FakeItEasy",
        "Magick.NET",
        "SkiaSharp",
        "Playwright",
        "Node.js",
        "Express.js",
        "Fastify.js",
        "Mongoose",
        "Prisma",
      ],
    },
    {
      category: "Databases & Caching",
      items: ["PostgreSQL", "MSSQL", "MongoDB", "Redis Cache"],
    },
    {
      category: "Cloud & DevOps",
      items: [
        "AWS (S3, EC2, RDS, SES)",
        "Hetzner",
        "Cloudflare",
        "Docker",
        "Nginx",
        "GitHub Actions",
        "CI/CD",
        "Ubuntu",
      ],
    },
    {
      category: "Communication & Real-Time",
      items: [
        "RabbitMQ",
        "Redis Pub/Sub",
        "WebSockets",
        "SignalR",
        "Socket.IO",
        "gRPC",
      ],
    },
  ],
  experience: [
    {
      role: "Backend Team Lead & DevOps Engineer",
      company: "Reseed Software",
      domain: "Customs",
      period: "Dec 2023 – Apr 2026",
      location: "Belgium (Remote)",
      highlights: [
        "Led backend development and DevOps operations.",
        "Initially, the project was built with Node.js (Fastify.js) and MongoDB. Later, I led the migration to .NET and PostgreSQL to support future scalability and long-term maintainability.",
        "Implemented dependency injection using Autofac.",
        "Implemented web scraping and automated screenshot generation using Playwright.",
        "Developed unit tests using XUnit and FakeItEasy.",
        "Migrated email infrastructure from AWS SES to Google services to reduce operational costs.",
        "Migrated infrastructure from AWS EC2/S3 to Hetzner servers and object storage to significantly reduce infrastructure costs.",
        "AWS RDS was used for database management.",
        "Implemented Redis caching to reduce database load and improve response times for frequently accessed shared tenant data.",
        "Implemented a refresh token mechanism to improve security and enable token revocation.",
        "Designed a scalable multi-tenant SaaS architecture with isolated databases per customer to improve data separation and tenant security.",
        "Built CI/CD deployment infrastructure using Docker, Nginx, GitHub Actions, and Ubuntu servers to streamline deployments and server management.",
        "Introduced queue-based architecture with RabbitMQ to offload heavy background processes and improve system scalability.",
        "Developed real-time communication infrastructure using Socket.IO, later migrating to SignalR after transitioning to .NET for live system updates and client synchronization.",
        "Developed an image-processing service using Magick.NET and SkiaSharp to enhance image quality and resolution.",
      ],
      stack: [
        ".NET",
        "Node.js",
        "Fastify.js",
        "MongoDB",
        "PostgreSQL",
        "RabbitMQ",
        "SignalR",
        "Socket.IO",
        "Docker",
        "Nginx",
        "Hetzner",
        "Redis",
        "AWS S3 - EC2 - RDS - SES",
        "Cloudflare",
        "XUnit",
        "FakeItEasy",
        "Autofac",
        "Playwright",
        "Magick.NET",
        "SkiaSharp",
      ],
    },
    {
      role: "Backend & DevOps Engineer",
      company: "Bahtrade",
      domain: "Finance",
      period: "Aug 2023 – Feb 2024",
      location: "Romania (Remote)",
      highlights: [
        "Responsible for backend development of the company’s main platform.",
        "Served as the company’s sole DevOps engineer.",
        "Configured and maintained cloud infrastructure, CI/ CD pipelines, and containerized deployments across approximately 20 Linux servers with using Ubuntu, Nginx, Docker, GitHub Actions, and AWS services including EC2, RDS, S3, and SES.",
        "Frequently communicated and prepared technical documentation and infrastructure diagrams to AWS Support to request service quota increases and production access approvals.",
        "Developed a large-scale real-time communication system using Socket.IO and WebSockets.",
      ],
      stack: [
        ".NET",
        "Node.js",
        "Express.js",
        "MSSQL",
        "SignalR",
        "Socket.IO",
        "Docker",
        "Nginx",
        "AWS S3 - EC2 - RDS - SES",
        "Cloudflare",
        "Autofac",
      ],
    },
    {
      role: "Backend Engineer",
      company: "Prime Tech",
      domain: "Finance",
      period: "Aug 2022 – Jul 2024",
      location: "Istanbul, Turkey",
      highlights: [
        "Separated monolith news platform into clean-architecture admin and microservice client apps",
        "Implemented Redis Pub/Sub for cross-service data synchronization",
        "Enabled inter-service communication via MediatR and gRPC",
        "Built API gateway access layer using Ocelot",
        "Integrated SignalR for real-time frontend updates",
        "Developed CRM system and live support with Socket.IO",
        "Implemented blockchain infrastructure for BTC, NEAR, DOGE with Node.js",
      ],
      stack: [
        ".NET",
        "PostgreSQL",
        "MSSQL",
        "Redis",
        "gRPC",
        "MediatR",
        "Ocelot",
        "MongoDB",
        "SignalR",
      ],
    },
    {
      role: "Backend & DevOps Engineer",
      company: "Wordigo",
      domain: "Startup",
      period: "Jun 2023 – Oct 2023",
      location: "Istanbul, Turkey",
      highlights: [
        "Built backend with Fastify.js in a tRPC mono-repo setup",
        "Managed data layer with Prisma ORM on PostgreSQL",
        "Integrated Google Cloud Storage for image uploads",
      ],
      stack: [
        "Node.js",
        "Fastify.js",
        "Prisma",
        "PostgreSQL",
        "Google Cloud Storage",
      ],
    },
    {
      role: "Backend Intern",
      company: "Naryex",
      domain: "Finance",
      period: "Jan 2022 – Aug 2022",
      location: "Istanbul, Turkey",
      highlights: [
        "Completed .NET Web API development coursework",
        "Delivered a Stock Management project for the accounting department",
        "Gained hands-on experience with Code First migrations in Entity Framework",
      ],
      stack: [".NET", "Entity Framework", "MSSQL"],
    },
  ],
  education: {
    degree: "Computer Engineering",
    school: "Istanbul Aydın University",
    period: "Oct 2020 – Jun 2024",
    location: "Istanbul, Turkey",
  },
  languages: ["Turkish (Native)", "English (Fluent)"],
};

export const NAV_ITEMS = [
  "About",
  "Skills",
  "Experience",
  "Education",
  "Contact",
] as const;
export type NavItem = (typeof NAV_ITEMS)[number];

export const STATS: Array<{ num: string; label: string }> = [
  { num: "4+", label: "Years experience" },
  { num: "5", label: "Companies" },
  { num: "28+", label: "Technologies" },
  { num: "2", label: "Languages" },
];
